name: ose-course-scientific-computing

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- black
- chaospy
- estimagic
- flake8
- ipython
- ipykernel
- jupyterlab
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- matplotlib
- nbsphinx
- nb_black
- numpy
- pandas
- pip
- pytest==5.4.3
- pytest-black
- pytest-flake8
- respy
- scipy
- simplegeneric
- scikit-learn
- seaborn
- sphinx>=1.4
- pip:
    - black-nb
    - flake8-nb
    - linearmodels
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-bibtex
