name: ose-course-scientific-computing

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- ipython
- ipykernel
- jupyterlab
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- black
- chaospy
- estimagic
- flake8
- matplotlib
- nbsphinx
- nb_black
- numpy
- pandas
- pip
- pytest
- respy
- scipy
- scikit-learn
- seaborn
- pip:
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
