name: ose-scientific-computing

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- numpy
- pandas
- nbsphinx
- pip
- pytest
- pytest-black
- pytest-flake8
- nb_black
- pip:
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
