name: ose-course-scientific-computing

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- numpy
- pandas
- nbsphinx
- pip
- pytest
- pytest-black
- pytest-flake8
- pip:
  - black-nb
  - flake8-nb
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
